### ISSUE TITLE
添加日志记录参数后，客户端无法联系上服务器

### ISSUE THREAD

**Issue by longdanie** [kuoruan/kcptun_installer#1]
我用的是v15版本，把 kcptun 部署于搬瓦工VPS后，正常运行。我想查看下 SNMP 信息，所以就使用脚本的直接修改配置文件功能，添加如下参数：
`"log": "/var/log/kcptun.log"`
修改好保存并重启 kcptun 服务端，然后本地客户端就连接不上服务器了。

**Comment by kuoruan** [comment]
由于新版本里边有配置kcptun启动用户的功能，存在着权限问题，所以我将log这个配置项给去掉了。
你如果想看日志的话，直接用 ```./kcptun.sh log```
其他的使用说明 ```./kcptun.sh help```

**Comment by longdanie** [comment]
我用了，但没有任何 SNMP 相关的信息呀，我是想调整最合适的参数才需要看SNMP信息的。昨天布置好 KCPTUN后，刚测试了一天，就把100G的流量配额用掉了24%。流量浪费太多，我想手工调整一下。

**Comment by kuoruan** [comment]
默认的日志文件在 ```/var/log/kcptun/``` 这个文件夹里边，你看看里边有文件没有

**Comment by longdanie** [comment]
里面只有一个 server.log 文件，该文件里面没有记录 SNMP 相关的信息。

**Comment by kuoruan** [comment]
你一直在说 SNMP，这是个什么东西？kcptun 的日志就输出那些东西啊，其他是不会输出的啊

**Comment by aqaqaqq** [comment]
楼主说的是kcptun项目首页有这么一句话：

使用kill -SIGUSR1 pid 可以在控制台打印出SNMP信息，通常用于精细调整当前链路的有效载荷比。
