### ISSUE TITLE
使用 “添加实例(多用户) ” 后无法使用supervisor管理新添加的实例

### ISSUE THREAD

**Issue by icbcbicc** [kuoruan/kcptun_installer#2]
supervisor只能管理第一个建立的实例，无法使用它控制其他实例进程。

**Comment by kuoruan** [comment]
具体表现是什么？

**Comment by icbcbicc** [comment]
使用supervisorctl start kcptun 或者supervisorctl stop kcptun 只对第一个建立的实例有效。

比如：当用supervisorctl stop kcptun后，第一个实例停止，但进程里还有第二个实例，并且无法通过再次输入supervisorctl stop kcptun来结束。

@kuoruan

**Comment by kuoruan** [comment]
```
./kcptun.sh help
supervisorctl status
supervisorctl stop kcptun
supervisorctl stop kcptun2
supervisorctl stop kcptun3
```
