### ISSUE TITLE
autoexpire参数

### ISSUE THREAD

**Issue by xiaofami** [kuoruan/kcptun_installer#3]
kcptun.sh没有提供修改autoexpire的选项，输出参数的结果中"autoexpire 60"是写死的。而且我到/usr/share/kcptun/server-config.json中查看了，没有autoexpire这个参数

可使用的客户端配置文件为:
	{
	    "localaddr": ":${target_port}",
	    "remoteaddr": "${SERVER_IP}:${listen_port}",
	    "key": "${key}",
	    "crypt": "${crypt}",
	    "mode": "${mode}",
	    "conn": 1,
	    "autoexpire": 60,
	    "mtu": ${mtu},
	    "sndwnd": ${rcvwnd},
	    "rcvwnd": ${sndwnd},
	    "datashard": ${datashard},
	    "parityshard": ${parityshard},
	    "dscp": ${dscp},
	    "nocomp": ${nocomp},
	    "acknodelay": ${acknodelay},
	    "nodelay": ${nodelay},
	    "interval": ${interval},
	    "resend": ${resend},
	    "nc": ${nc},
	    "sockbuf": ${sockbuf},
	    "keepalive": ${keepalive}
	}

**Comment by kuoruan** [comment]
autoexpire 只对客户端有用，服务端用不着
